force-app/main/default/objects/Bowling_Game__c/Bowling_Game__c.object-meta.xml
<CustomObject>
    <description>Object to store game scores</description>
    <label>Bowling Game</label>
    <nameField>
        <displayFormat>Game-{0000}</displayFormat>
        <label>Game</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bowling Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bowling_Game__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bowling Games</relationshipLabel>
    <relationshipName>Bowling_Games</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bowling_Game__c/fields/Total_Score__c.field-meta.xml
<CustomField>
    <fullName>Total_Score__c</fullName>
    <label>Total Score</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GameService.cls
public with sharing class GameService {
  @AuraEnabled
  public static Contact getExistingPlayer(String name) {
    try {
      List<Contact> playerList = [
        SELECT Id, LastName
        FROM Contact
        WHERE Name = :name
      ];

      if (playerList.isEmpty()) {
        return null;
      } else {
        return playerList.get(0);
      }
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled
  public static List<Bowling_Game__c> getPreviousScores() {
    try {
      return [
        SELECT Id, Name, Total_Score__c, Player__r.Name
        FROM Bowling_Game__c
        ORDER BY Name DESC
        LIMIT 10
      ];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}